---
- hosts: '{{ hosts }}'
  gather_facts: yes
  serial: 1
  vars_files:
  - ~/.apigee/credentials.yml
  roles:
  - apigee-opdk-setup-default-settings
  - { role: apigee-opdk-backup, component_profile: '{{ component_name }}' }
